version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
build_project:
    working_directory: ~/circle-ci-s3-deploy
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run: 
          name: Installing dependencies
          command: yarn
      - run: 
          name: Building project
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  build_test:
    jobs:
      - build_project
