version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build_project:
    working_directory: ~/circle-ci-s3-deploy
    docker:
      - image: node:16.16.0
    steps:
      - checkout
      - run: 
          name: Installing dependencies
          command: npm install --save
      - run: 
          name: Building project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  build_test:
    jobs:
      - build_project
