version: 2.1
jobs:
  build_project:
    working_directory: ~/circle-ci-s3-deploy
    docker:
      - image: node:16.16.0
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm
      - run:
          name: Building project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload file to S3
          command: aws s3 sync ./dist/ s3://circleci-s3-integration-bucket --delete
workflows:
  version: 2
  build:
    jobs:
      - build_project:
          filters:
              branches:
                ignore: /.*/
              tags:
                only: /.*/

      - deploy_project:
          requires:
            - build_project
          context: aws-context
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/