version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build_project:
    working_directory: ~/circle-ci-s3-deploy
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run: 
          name: Installing dependencies
          command: npm install
      - run: 
          name: Building project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: am-cloud-admin-ops
      - run:
          name: Upload file to S3
          command: |
            if [[ $CIRCLE_BRANCH == "main" ]]; then
              echo "Deploying to main s3 bucket!"
              aws s3 sync ./dist s3://circleci-s3-cloudfront-integration-static-resources --delete 
            else
              echo "Deploying to staging s3 bucket!"
              aws s3 sync ./dist s3://circleci-s3-cloudfront-integration-staging-static-resources --delete 
            fi
                 
workflows:
  build_test:
    jobs:
      - build_project:
          filters:
            branches:
              only:
                - main
      - deploy_project:
          requires:
            - build_project
          context: aws-context
